from ctypes import *



ER_FT_MATCHING_KEY_NOT_FOUND = 1191 # Variable c_int '1191'
ER_EVENT_DROP_FAILED = 1541 # Variable c_int '1541'
ER_VIEW_CHECKSUM = 1392 # Variable c_int '1392'
ER_BAD_FIELD_ERROR = 1054 # Variable c_int '1054'
ER_DROP_FILEGROUP_FAILED = 1529 # Variable c_int '1529'
ER_WRONG_KEY_COLUMN = 1167 # Variable c_int '1167'
ER_VAR_CANT_BE_READ = 1233 # Variable c_int '1233'
ER_CANT_USE_OPTION_HERE = 1234 # Variable c_int '1234'
ER_NATIVE_FCT_NAME_COLLISION = 1585 # Variable c_int '1585'
ER_MASTER_INFO = 1201 # Variable c_int '1201'
ER_FILEGROUP_OPTION_ONLY_ONCE = 1527 # Variable c_int '1527'
ER_NET_PACKETS_OUT_OF_ORDER = 1156 # Variable c_int '1156'
ER_SERVER_IS_IN_SECURE_AUTH_MODE = 1275 # Variable c_int '1275'
ER_RECORD_FILE_FULL = 1114 # Variable c_int '1114'
ER_IO_ERR_LOG_INDEX_READ = 1374 # Variable c_int '1374'
ER_TOO_BIG_SET = 1097 # Variable c_int '1097'
ER_NO_PARTITION_FOR_GIVEN_VALUE_SILENT = 1591 # Variable c_int '1591'
ER_ERROR_WHEN_EXECUTING_COMMAND = 1220 # Variable c_int '1220'
ER_PARTITION_REQUIRES_VALUES_ERROR = 1479 # Variable c_int '1479'
ER_ERROR_ON_RENAME = 1025 # Variable c_int '1025'
ER_PARTITION_WRONG_NO_SUBPART_ERROR = 1485 # Variable c_int '1485'
ER_NO_DEFAULT_FOR_VIEW_FIELD = 1423 # Variable c_int '1423'
ER_STARTUP = 1408 # Variable c_int '1408'
ER_SP_RECURSION_LIMIT = 1456 # Variable c_int '1456'
ER_WRONG_PARTITION_NAME = 1567 # Variable c_int '1567'
ER_PROC_AUTO_GRANT_FAIL = 1404 # Variable c_int '1404'
ER_FORBID_SCHEMA_CHANGE = 1450 # Variable c_int '1450'
ER_SP_WRONG_NO_OF_FETCH_ARGS = 1328 # Variable c_int '1328'
ER_NO_SUCH_TABLE = 1146 # Variable c_int '1146'
ER_WARNING_NOT_COMPLETE_ROLLBACK = 1196 # Variable c_int '1196'
ER_SUBQUERY_NO_1_ROW = 1242 # Variable c_int '1242'
ER_VIEW_NO_INSERT_FIELD_LIST = 1394 # Variable c_int '1394'
ER_WRONG_FIELD_WITH_GROUP = 1055 # Variable c_int '1055'
ER_WRONG_FIELD_TERMINATORS = 1083 # Variable c_int '1083'
ER_CANT_WRITE_LOCK_LOG_TABLE = 1555 # Variable c_int '1555'
ER_BLOB_CANT_HAVE_DEFAULT = 1101 # Variable c_int '1101'
ER_ERROR_ON_READ = 1024 # Variable c_int '1024'
ER_ADMIN_WRONG_MRG_TABLE = 1472 # Variable c_int '1472'
ER_NO_TRIGGERS_ON_SYSTEM_SCHEMA = 1465 # Variable c_int '1465'
ER_NO_PARTITION_FOR_GIVEN_VALUE = 1526 # Variable c_int '1526'
ER_NONEXISTING_TABLE_GRANT = 1147 # Variable c_int '1147'
ER_WRONG_MAGIC = 1389 # Variable c_int '1389'
ER_TOO_BIG_FIELDLENGTH = 1074 # Variable c_int '1074'
ER_DERIVED_MUST_HAVE_ALIAS = 1248 # Variable c_int '1248'
ER_VIEW_CHECK_FAILED = 1369 # Variable c_int '1369'
ER_CHECK_NOT_IMPLEMENTED = 1178 # Variable c_int '1178'
ER_BLOB_FIELD_IN_PART_FUNC_ERROR = 1502 # Variable c_int '1502'
ER_MULTIPLE_PRI_KEY = 1068 # Variable c_int '1068'
ER_SLAVE_MUST_STOP = 1198 # Variable c_int '1198'
ER_ROW_IS_REFERENCED_2 = 1451 # Variable c_int '1451'
ER_DELAYED_NOT_SUPPORTED = 1616 # Variable c_int '1616'
ER_GET_TEMPORARY_ERRMSG = 1297 # Variable c_int '1297'
ER_TRG_NO_CREATION_CTX = 1603 # Variable c_int '1603'
ER_NET_READ_INTERRUPTED = 1159 # Variable c_int '1159'
ER_WRONG_AUTO_KEY = 1075 # Variable c_int '1075'
ER_EVENTS_DB_ERROR = 1577 # Variable c_int '1577'
ER_WSAS_FAILED = 1383 # Variable c_int '1383'
ER_VIEW_NONUPD_CHECK = 1368 # Variable c_int '1368'
ER_REQUIRES_PRIMARY_KEY = 1173 # Variable c_int '1173'
ER_RELAY_LOG_INIT = 1380 # Variable c_int '1380'
ER_LOCK_TABLE_FULL = 1206 # Variable c_int '1206'
ER_MAX_PREPARED_STMT_COUNT_REACHED = 1461 # Variable c_int '1461'
ER_DB_CREATE_EXISTS = 1007 # Variable c_int '1007'
ER_CORRUPT_HELP_DB = 1244 # Variable c_int '1244'
ER_TOO_MANY_DELAYED_THREADS = 1151 # Variable c_int '1151'
ER_SP_LABEL_REDEFINE = 1309 # Variable c_int '1309'
ER_PS_MANY_PARAM = 1390 # Variable c_int '1390'
ER_ILLEGAL_REFERENCE = 1247 # Variable c_int '1247'
ER_ERROR_LAST = 1616 # Variable c_int '1616'
ER_HANDSHAKE_ERROR = 1043 # Variable c_int '1043'
ER_SP_DUP_HANDLER = 1413 # Variable c_int '1413'
ER_WRONG_VALUE_COUNT = 1058 # Variable c_int '1058'
ER_READ_ONLY_TRANSACTION = 1207 # Variable c_int '1207'
ER_CANT_ACTIVATE_LOG = 1573 # Variable c_int '1573'
ER_MASTER = 1188 # Variable c_int '1188'
ER_ONLY_ON_RANGE_LIST_PARTITION = 1512 # Variable c_int '1512'
ER_TRUNCATED_WRONG_VALUE = 1292 # Variable c_int '1292'
ER_NO_DEFAULT = 1230 # Variable c_int '1230'
ER_NOT_SUPPORTED_AUTH_MODE = 1251 # Variable c_int '1251'
ER_DISK_FULL = 1021 # Variable c_int '1021'
ER_LIST_OF_FIELDS_ONLY_IN_HASH_ERROR = 1489 # Variable c_int '1489'
ER_EVENT_COMPILE_ERROR = 1550 # Variable c_int '1550'
ER_FORM_NOT_FOUND = 1029 # Variable c_int '1029'
ER_SP_FETCH_NO_DATA = 1329 # Variable c_int '1329'
ER_CANT_FIND_DL_ENTRY = 1127 # Variable c_int '1127'
ER_WARN_USING_OTHER_HANDLER = 1266 # Variable c_int '1266'
ER_LOG_IN_USE = 1378 # Variable c_int '1378'
ER_REORG_HASH_ONLY_ON_SAME_NO = 1510 # Variable c_int '1510'
ER_SP_DOES_NOT_EXIST = 1305 # Variable c_int '1305'
ER_PASSWORD_ANONYMOUS_USER = 1131 # Variable c_int '1131'
ER_VIEW_MULTIUPDATE = 1393 # Variable c_int '1393'
ER_SP_NO_RECURSION = 1424 # Variable c_int '1424'
ER_PARTITION_SUBPARTITION_ERROR = 1482 # Variable c_int '1482'
ER_VIEW_SELECT_DERIVED = 1349 # Variable c_int '1349'
ER_ALTER_FILEGROUP_FAILED = 1533 # Variable c_int '1533'
ER_TRG_CANT_OPEN_TABLE = 1606 # Variable c_int '1606'
ER_CANT_REMOVE_ALL_FIELDS = 1090 # Variable c_int '1090'
ER_WRONG_VALUE_FOR_TYPE = 1411 # Variable c_int '1411'
ER_FOREIGN_KEY_ON_PARTITIONED = 1506 # Variable c_int '1506'
ER_BLOB_KEY_WITHOUT_LENGTH = 1170 # Variable c_int '1170'
ER_VIEW_NO_EXPLAIN = 1345 # Variable c_int '1345'
ER_WARN_VIEW_WITHOUT_KEY = 1355 # Variable c_int '1355'
ER_PRIMARY_CANT_HAVE_NULL = 1171 # Variable c_int '1171'
ER_NO_GROUP_FOR_PROC = 1385 # Variable c_int '1385'
ER_TABLE_CANT_HANDLE_AUTO_INCREMENT = 1164 # Variable c_int '1164'
ER_KEY_NOT_FOUND = 1032 # Variable c_int '1032'
ER_WARN_QC_RESIZE = 1282 # Variable c_int '1282'
ER_INVALID_CHARACTER_STRING = 1300 # Variable c_int '1300'
ER_NOT_FORM_FILE = 1033 # Variable c_int '1033'
ER_INCORRECT_GLOBAL_LOCAL_VAR = 1238 # Variable c_int '1238'
ER_TOO_MANY_USER_CONNECTIONS = 1203 # Variable c_int '1203'
ER_CANT_GET_STAT = 1013 # Variable c_int '1013'
ER_KILL_DENIED_ERROR = 1095 # Variable c_int '1095'
ER_TRANS_CACHE_FULL = 1197 # Variable c_int '1197'
ER_FOREIGN_SERVER_DOESNT_EXIST = 1477 # Variable c_int '1477'
ER_SP_CASE_NOT_FOUND = 1339 # Variable c_int '1339'
ER_TOO_BIG_SCALE = 1425 # Variable c_int '1425'
ER_BINLOG_LOGGING_IMPOSSIBLE = 1598 # Variable c_int '1598'
ER_YES = 1003 # Variable c_int '1003'
ER_CHECK_NO_SUCH_TABLE = 1177 # Variable c_int '1177'
ER_SLAVE_CORRUPT_EVENT = 1610 # Variable c_int '1610'
ER_BASE64_DECODE_ERROR = 1575 # Variable c_int '1575'
ER_PARTITION_WRONG_VALUES_ERROR = 1480 # Variable c_int '1480'
ER_SP_NO_RECURSIVE_CREATE = 1303 # Variable c_int '1303'
ER_NON_INSERTABLE_TABLE = 1471 # Variable c_int '1471'
ER_SLAVE_FATAL_ERROR = 1593 # Variable c_int '1593'
ER_TOO_MANY_FIELDS = 1117 # Variable c_int '1117'
ER_WRONG_NAME_FOR_INDEX = 1280 # Variable c_int '1280'
ER_UNKNOWN_TARGET_BINLOG = 1373 # Variable c_int '1373'
ER_GET_ERRMSG = 1296 # Variable c_int '1296'
ER_XAER_RMFAIL = 1399 # Variable c_int '1399'
ER_MALFORMED_DEFINER = 1446 # Variable c_int '1446'
ER_SP_NOT_VAR_ARG = 1414 # Variable c_int '1414'
ER_CONST_EXPR_IN_PARTITION_FUNC_ERROR = 1486 # Variable c_int '1486'
ER_WRONG_GROUP_FIELD = 1056 # Variable c_int '1056'
ER_TABLE_CANT_HANDLE_SPKEYS = 1464 # Variable c_int '1464'
ER_BAD_LOG_STATEMENT = 1580 # Variable c_int '1580'
ER_TOO_BIG_FOR_UNCOMPRESS = 1256 # Variable c_int '1256'
ER_PART_STATE_ERROR = 1522 # Variable c_int '1522'
ER_FAILED_ROUTINE_BREAK_BINLOG = 1417 # Variable c_int '1417'
ER_BAD_HOST_ERROR = 1042 # Variable c_int '1042'
ER_EXEC_STMT_WITH_OPEN_CURSOR = 1420 # Variable c_int '1420'
ER_REVOKE_GRANTS = 1269 # Variable c_int '1269'
ER_LOAD_FROM_FIXED_SIZE_ROWS_TO_VAR = 1409 # Variable c_int '1409'
ER_SP_CURSOR_ALREADY_OPEN = 1325 # Variable c_int '1325'
ER_DROP_USER = 1268 # Variable c_int '1268'
ER_NO = 1002 # Variable c_int '1002'
ER_NET_WRITE_INTERRUPTED = 1161 # Variable c_int '1161'
ER_SP_NO_DROP_SP = 1357 # Variable c_int '1357'
ER_RBR_NOT_AVAILABLE = 1574 # Variable c_int '1574'
ER_FIELD_SPECIFIED_TWICE = 1110 # Variable c_int '1110'
ER_INVALID_USE_OF_NULL = 1138 # Variable c_int '1138'
ER_WARN_HOSTNAME_WONT_WORK = 1285 # Variable c_int '1285'
ER_CANT_UPDATE_USED_TABLE_IN_SF_OR_TRG = 1442 # Variable c_int '1442'
ER_TRG_INVALID_CREATION_CTX = 1604 # Variable c_int '1604'
ER_UNKNOWN_TIME_ZONE = 1298 # Variable c_int '1298'
ER_SP_BAD_CURSOR_QUERY = 1322 # Variable c_int '1322'
ER_FOREIGN_DATA_STRING_INVALID_CANT_CREATE = 1432 # Variable c_int '1432'
ER_ONLY_INTEGERS_ALLOWED = 1578 # Variable c_int '1578'
ER_CRASHED_ON_REPAIR = 1195 # Variable c_int '1195'
ER_SP_BAD_VAR_SHADOW = 1453 # Variable c_int '1453'
ER_NET_ERROR_ON_WRITE = 1160 # Variable c_int '1160'
ER_ILLEGAL_HA_CREATE_OPTION = 1478 # Variable c_int '1478'
ER_DELAYED_CANT_CHANGE_LOCK = 1150 # Variable c_int '1150'
ER_NO_BINARY_LOGGING = 1381 # Variable c_int '1381'
ER_DUP_ENTRY_WITH_KEY_NAME = 1586 # Variable c_int '1586'
ER_ZLIB_Z_MEM_ERROR = 1257 # Variable c_int '1257'
ER_TOO_MUCH_AUTO_TIMESTAMP_COLS = 1293 # Variable c_int '1293'
ER_REORG_PARTITION_NOT_EXIST = 1516 # Variable c_int '1516'
ER_FRM_UNKNOWN_TYPE = 1346 # Variable c_int '1346'
ER_PARTITION_CONST_DOMAIN_ERROR = 1563 # Variable c_int '1563'
ER_TABLEACCESS_DENIED_ERROR = 1142 # Variable c_int '1142'
ER_ILLEGAL_HA = 1031 # Variable c_int '1031'
ER_WRONG_VALUE_FOR_VAR = 1231 # Variable c_int '1231'
ER_PARTITION_FUNCTION_FAILURE = 1521 # Variable c_int '1521'
ER_PASSWD_LENGTH = 1372 # Variable c_int '1372'
ER_SP_SUBSELECT_NYI = 1335 # Variable c_int '1335'
ER_NOT_SUPPORTED_YET = 1235 # Variable c_int '1235'
ER_WARN_CANT_DROP_DEFAULT_KEYCACHE = 1438 # Variable c_int '1438'
ER_COL_COUNT_DOESNT_MATCH_CORRUPTED = 1547 # Variable c_int '1547'
ER_UPDATE_TABLE_USED = 1093 # Variable c_int '1093'
ER_UNTIL_COND_IGNORED = 1279 # Variable c_int '1279'
ER_CANNOT_USER = 1396 # Variable c_int '1396'
ER_KEY_REF_DO_NOT_MATCH_TABLE_REF = 1240 # Variable c_int '1240'
ER_WRONG_SUM_SELECT = 1057 # Variable c_int '1057'
ER_PARTITION_MAXVALUE_ERROR = 1481 # Variable c_int '1481'
ER_DUP_ENTRY = 1062 # Variable c_int '1062'
ER_STMT_HAS_NO_OPEN_CURSOR = 1421 # Variable c_int '1421'
ER_TOO_MANY_ROWS = 1172 # Variable c_int '1172'
ER_LOAD_INFO = 1087 # Variable c_int '1087'
ER_WRONG_PARAMETERS_TO_STORED_FCT = 1584 # Variable c_int '1584'
ER_FOREIGN_DATA_SOURCE_DOESNT_EXIST = 1431 # Variable c_int '1431'
ER_CANT_LOCK_LOG_TABLE = 1556 # Variable c_int '1556'
ER_EVENT_STORE_FAILED = 1538 # Variable c_int '1538'
ER_SLAVE_MASTER_COM_FAILURE = 1597 # Variable c_int '1597'
ER_ABORTING_CONNECTION = 1152 # Variable c_int '1152'
ER_DDL_LOG_ERROR = 1565 # Variable c_int '1565'
ER_BINLOG_ROW_RBR_TO_SBR = 1536 # Variable c_int '1536'
ER_FILE_EXISTS_ERROR = 1086 # Variable c_int '1086'
ER_REORG_OUTSIDE_RANGE = 1520 # Variable c_int '1520'
ER_EMPTY_QUERY = 1065 # Variable c_int '1065'
ER_SP_LABEL_MISMATCH = 1310 # Variable c_int '1310'
ER_ILLEGAL_GRANT_FOR_TABLE = 1144 # Variable c_int '1144'
ER_REGEXP_ERROR = 1139 # Variable c_int '1139'
ER_VIEW_RECURSIVE = 1462 # Variable c_int '1462'
ER_LOGGING_PROHIBIT_CHANGING_OF = 1387 # Variable c_int '1387'
ER_WRONG_PARAMCOUNT_TO_NATIVE_FCT = 1582 # Variable c_int '1582'
ER_NO_PARTS_ERROR = 1504 # Variable c_int '1504'
ER_RELAY_LOG_FAIL = 1371 # Variable c_int '1371'
ER_BINLOG_ROW_LOGGING_FAILED = 1534 # Variable c_int '1534'
ER_TRG_NO_SUCH_ROW_IN_TRG = 1363 # Variable c_int '1363'
ER_NON_UNIQ_ERROR = 1052 # Variable c_int '1052'
ER_RESERVED_SYNTAX = 1382 # Variable c_int '1382'
ER_INVALID_ON_UPDATE = 1294 # Variable c_int '1294'
ER_WARN_NULL_TO_NOTNULL = 1263 # Variable c_int '1263'
ER_XA_RBDEADLOCK = 1614 # Variable c_int '1614'
ER_NO_DB_ERROR = 1046 # Variable c_int '1046'
ER_EVENT_ALREADY_EXISTS = 1537 # Variable c_int '1537'
ER_CREATE_DB_WITH_READ_LOCK = 1209 # Variable c_int '1209'
ER_SP_DUP_CURS = 1333 # Variable c_int '1333'
ER_DUPLICATED_VALUE_IN_TYPE = 1291 # Variable c_int '1291'
ER_DUP_UNIQUE = 1169 # Variable c_int '1169'
ER_UNKNOWN_TABLE = 1109 # Variable c_int '1109'
ER_TOO_MANY_KEY_PARTS = 1070 # Variable c_int '1070'
ER_FILE_USED = 1027 # Variable c_int '1027'
ER_SP_VARCOND_AFTER_CURSHNDLR = 1337 # Variable c_int '1337'
ER_LOCAL_VARIABLE = 1228 # Variable c_int '1228'
ER_BINLOG_PURGE_PROHIBITED = 1375 # Variable c_int '1375'
ER_SP_CANT_ALTER = 1334 # Variable c_int '1334'
ER_PARTITION_SUBPART_MIX_ERROR = 1483 # Variable c_int '1483'
ER_CONNECT_TO_FOREIGN_DATA_SOURCE = 1429 # Variable c_int '1429'
ER_WRONG_PARAMETERS_TO_PROCEDURE = 1108 # Variable c_int '1108'
ER_UNSUPPORTED_PS = 1295 # Variable c_int '1295'
ER_INDEX_REBUILD = 1187 # Variable c_int '1187'
ER_PASSWORD_NOT_ALLOWED = 1132 # Variable c_int '1132'
ER_BAD_TABLE_ERROR = 1051 # Variable c_int '1051'
ER_WRONG_PARAMETERS_TO_NATIVE_FCT = 1583 # Variable c_int '1583'
ER_NET_PACKET_TOO_LARGE = 1153 # Variable c_int '1153'
ER_NAME_BECOMES_EMPTY = 1474 # Variable c_int '1474'
ER_WRONG_PARAMCOUNT_TO_PROCEDURE = 1107 # Variable c_int '1107'
ER_BAD_SLAVE = 1200 # Variable c_int '1200'
ER_EVENT_EXEC_TIME_IN_THE_PAST = 1544 # Variable c_int '1544'
ER_WRONG_VALUE_COUNT_ON_ROW = 1136 # Variable c_int '1136'
ER_NET_READ_ERROR = 1158 # Variable c_int '1158'
ER_AMBIGUOUS_FIELD_TERM = 1475 # Variable c_int '1475'
ER_CONSECUTIVE_REORG_PARTITIONS = 1519 # Variable c_int '1519'
ER_CANT_DELETE_FILE = 1011 # Variable c_int '1011'
WARN_DATA_TRUNCATED = 1265 # Variable c_int '1265'
ER_SP_NO_AGGREGATE = 1460 # Variable c_int '1460'
ER_WARN_INVALID_TIMESTAMP = 1299 # Variable c_int '1299'
ER_CANT_CREATE_USER_WITH_GRANT = 1410 # Variable c_int '1410'
ER_CANT_DO_THIS_DURING_AN_TRANSACTION = 1179 # Variable c_int '1179'
ER_PARTITION_MGMT_ON_NONPARTITIONED = 1505 # Variable c_int '1505'
ER_WRONG_FK_DEF = 1239 # Variable c_int '1239'
ER_DATETIME_FUNCTION_OVERFLOW = 1441 # Variable c_int '1441'
ER_REMOVED_SPACES = 1466 # Variable c_int '1466'
ER_NONEXISTING_GRANT = 1141 # Variable c_int '1141'
ER_ADD_PARTITION_SUBPART_ERROR = 1513 # Variable c_int '1513'
ER_NO_REFERENCED_ROW_2 = 1452 # Variable c_int '1452'
ER_SLAVE_RELAY_LOG_READ_FAILURE = 1594 # Variable c_int '1594'
ER_NO_BINLOG_ERROR = 1518 # Variable c_int '1518'
ER_GOT_SIGNAL = 1078 # Variable c_int '1078'
ER_SHUTDOWN_COMPLETE = 1079 # Variable c_int '1079'
ER_WRONG_TYPE_FOR_VAR = 1232 # Variable c_int '1232'
ER_DUP_ARGUMENT = 1225 # Variable c_int '1225'
ER_SP_NORETURNEND = 1321 # Variable c_int '1321'
ER_CANT_LOCK = 1015 # Variable c_int '1015'
ER_TABLE_DEF_CHANGED = 1412 # Variable c_int '1412'
ER_WRONG_SUB_KEY = 1089 # Variable c_int '1089'
ER_SYNTAX_ERROR = 1149 # Variable c_int '1149'
ER_WARN_TOO_FEW_RECORDS = 1261 # Variable c_int '1261'
ER_VARIABLE_IS_NOT_STRUCT = 1272 # Variable c_int '1272'
ER_AUTOINC_READ_FAILED = 1467 # Variable c_int '1467'
ER_TOO_LONG_IDENT = 1059 # Variable c_int '1059'
ER_SP_COND_MISMATCH = 1319 # Variable c_int '1319'
ER_STORED_FUNCTION_PREVENTS_SWITCH_BINLOG_FORMAT = 1560 # Variable c_int '1560'
ER_ERROR_DURING_ROLLBACK = 1181 # Variable c_int '1181'
ER_MIXING_NOT_ALLOWED = 1224 # Variable c_int '1224'
ER_TABLE_NOT_LOCKED_FOR_WRITE = 1099 # Variable c_int '1099'
ER_OLD_KEYFILE = 1035 # Variable c_int '1035'
ER_BINLOG_ROW_WRONG_TABLE_DEF = 1535 # Variable c_int '1535'
ER_CANT_AGGREGATE_3COLLATIONS = 1270 # Variable c_int '1270'
ER_SP_BAD_CURSOR_SELECT = 1323 # Variable c_int '1323'
ER_NON_GROUPING_FIELD_USED = 1463 # Variable c_int '1463'
ER_DROP_DB_WITH_READ_LOCK = 1208 # Variable c_int '1208'
ER_SERVER_SHUTDOWN = 1053 # Variable c_int '1053'
ER_M_BIGGER_THAN_D = 1427 # Variable c_int '1427'
ER_TOO_LONG_STRING = 1162 # Variable c_int '1162'
ER_OLD_FILE_FORMAT = 1455 # Variable c_int '1455'
ER_EVENT_ENDS_BEFORE_STARTS = 1543 # Variable c_int '1543'
ER_COALESCE_PARTITION_NO_PARTITION = 1515 # Variable c_int '1515'
ER_NOT_ALLOWED_COMMAND = 1148 # Variable c_int '1148'
ER_VIEW_INVALID_CREATION_CTX = 1600 # Variable c_int '1600'
ER_UNSUPORTED_LOG_ENGINE = 1579 # Variable c_int '1579'
ER_MIX_OF_GROUP_FUNC_AND_FIELDS = 1140 # Variable c_int '1140'
ER_DUP_KEY = 1022 # Variable c_int '1022'
ER_UNKNOWN_COM_ERROR = 1047 # Variable c_int '1047'
ER_SP_DUP_VAR = 1331 # Variable c_int '1331'
ER_TEMP_TABLE_PREVENTS_SWITCH_OUT_OF_RBR = 1559 # Variable c_int '1559'
ER_SLAVE_NOT_RUNNING = 1199 # Variable c_int '1199'
ER_BINLOG_CREATE_ROUTINE_NEED_SUPER = 1419 # Variable c_int '1419'
ER_KEY_COLUMN_DOES_NOT_EXITS = 1072 # Variable c_int '1072'
ER_FILE_NOT_FOUND = 1017 # Variable c_int '1017'
ER_UNKNOWN_COLLATION = 1273 # Variable c_int '1273'
ER_WARN_VIEW_MERGE = 1354 # Variable c_int '1354'
ER_VIEW_NO_CREATION_CTX = 1599 # Variable c_int '1599'
ER_NO_PERMISSION_TO_CREATE_USER = 1211 # Variable c_int '1211'
ER_TOO_MANY_TABLES = 1116 # Variable c_int '1116'
ER_STACK_OVERRUN_NEED_MORE = 1436 # Variable c_int '1436'
ER_SP_DUP_PARAM = 1330 # Variable c_int '1330'
ER_EVENT_SET_VAR_ERROR = 1571 # Variable c_int '1571'
ER_WRONG_LOCK_OF_SYSTEM_TABLE = 1428 # Variable c_int '1428'
ER_TABLE_CANT_HANDLE_BLOB = 1163 # Variable c_int '1163'
ER_UNKNOWN_PROCEDURE = 1106 # Variable c_int '1106'
ER_UNEXPECTED_EOF = 1039 # Variable c_int '1039'
ER_ROW_IS_REFERENCED = 1217 # Variable c_int '1217'
ER_CANT_REOPEN_TABLE = 1137 # Variable c_int '1137'
ER_EVENT_OPEN_TABLE_FAILED = 1545 # Variable c_int '1545'
ER_TABLE_EXISTS_ERROR = 1050 # Variable c_int '1050'
ER_TABLENAME_NOT_ALLOWED_HERE = 1250 # Variable c_int '1250'
ER_EVENT_INVALID_CREATION_CTX = 1605 # Variable c_int '1605'
ER_PASSWORD_NO_MATCH = 1133 # Variable c_int '1133'
ER_XAER_INVAL = 1398 # Variable c_int '1398'
ER_NO_REFERENCED_ROW = 1216 # Variable c_int '1216'
ER_CANT_SET_WD = 1019 # Variable c_int '1019'
ER_NET_FCNTL_ERROR = 1155 # Variable c_int '1155'
ER_SAME_NAME_PARTITION = 1517 # Variable c_int '1517'
ER_PARTITION_NOT_DEFINED_ERROR = 1498 # Variable c_int '1498'
ER_WRONG_NUMBER_OF_COLUMNS_IN_SELECT = 1222 # Variable c_int '1222'
ER_GET_ERRNO = 1030 # Variable c_int '1030'
ER_EVENT_CANNOT_CREATE_IN_THE_PAST = 1588 # Variable c_int '1588'
ER_DB_DROP_DELETE = 1009 # Variable c_int '1009'
ER_BAD_NULL_ERROR = 1048 # Variable c_int '1048'
ER_CANT_CREATE_FILE = 1004 # Variable c_int '1004'
ER_SLAVE_WAS_RUNNING = 1254 # Variable c_int '1254'
ER_CONNECT_TO_MASTER = 1218 # Variable c_int '1218'
ER_CANT_OPEN_LIBRARY = 1126 # Variable c_int '1126'
ER_DATA_TOO_LONG = 1406 # Variable c_int '1406'
ER_ZLIB_Z_BUF_ERROR = 1258 # Variable c_int '1258'
ER_SLAVE_CREATE_EVENT_FAILURE = 1596 # Variable c_int '1596'
ER_UPDATE_WITHOUT_KEY_IN_SAFE_MODE = 1175 # Variable c_int '1175'
ER_NET_READ_ERROR_FROM_PIPE = 1154 # Variable c_int '1154'
ER_WRONG_COLUMN_NAME = 1166 # Variable c_int '1166'
ER_EVENT_NEITHER_M_EXPR_NOR_M_AT = 1546 # Variable c_int '1546'
ER_NEW_ABORTING_CONNECTION = 1184 # Variable c_int '1184'
ER_INVALID_DEFAULT = 1067 # Variable c_int '1067'
ER_NONEXISTING_PROC_GRANT = 1403 # Variable c_int '1403'
ER_TABLE_NEEDS_UPGRADE = 1459 # Variable c_int '1459'
ER_BAD_FT_COLUMN = 1283 # Variable c_int '1283'
ER_MASTER_FATAL_ERROR_READING_BINLOG = 1236 # Variable c_int '1236'
ER_NET_UNCOMPRESS_ERROR = 1157 # Variable c_int '1157'
ER_TOO_MANY_KEYS = 1069 # Variable c_int '1069'
ER_COALESCE_ONLY_ON_HASH_PARTITION = 1509 # Variable c_int '1509'
ER_OUTOFMEMORY = 1037 # Variable c_int '1037'
ER_CHECKREAD = 1020 # Variable c_int '1020'
ER_SP_BADSELECT = 1312 # Variable c_int '1312'
ER_CANT_READ_DIR = 1018 # Variable c_int '1018'
ER_EVENT_CANT_ALTER = 1540 # Variable c_int '1540'
ER_GRANT_WRONG_HOST_OR_USER = 1145 # Variable c_int '1145'
ER_SP_UNDECLARED_VAR = 1327 # Variable c_int '1327'
ER_FIELD_NOT_FOUND_PART_ERROR = 1488 # Variable c_int '1488'
ER_PARTITION_FUNC_NOT_ALLOWED_ERROR = 1491 # Variable c_int '1491'
ER_SR_INVALID_CREATION_CTX = 1601 # Variable c_int '1601'
ER_VIEW_DELETE_MERGE_VIEW = 1395 # Variable c_int '1395'
ER_UPDATE_LOG_DEPRECATED_TRANSLATED = 1316 # Variable c_int '1316'
ER_CANT_CREATE_FEDERATED_TABLE = 1434 # Variable c_int '1434'
ER_CANNOT_ADD_FOREIGN = 1215 # Variable c_int '1215'
ER_CANT_FIND_SYSTEM_REC = 1012 # Variable c_int '1012'
ER_EVENT_RECURSION_FORBIDDEN = 1576 # Variable c_int '1576'
ER_VIEW_FRM_NO_USER = 1447 # Variable c_int '1447'
ER_COMMIT_NOT_ALLOWED_IN_SF_OR_TRG = 1422 # Variable c_int '1422'
ER_DUMP_NOT_IMPLEMENTED = 1185 # Variable c_int '1185'
ER_WRONG_TABLE_NAME = 1103 # Variable c_int '1103'
ER_CANT_FIND_UDF = 1122 # Variable c_int '1122'
ER_NORMAL_SHUTDOWN = 1077 # Variable c_int '1077'
ER_INCONSISTENT_PARTITION_INFO_ERROR = 1490 # Variable c_int '1490'
ER_NO_SUCH_INDEX = 1082 # Variable c_int '1082'
ER_TOO_BIG_ROWSIZE = 1118 # Variable c_int '1118'
ER_NO_UNIQUE_LOGFILE = 1098 # Variable c_int '1098'
ER_XAER_OUTSIDE = 1400 # Variable c_int '1400'
ER_CYCLIC_REFERENCE = 1245 # Variable c_int '1245'
ER_PARTITIONS_MUST_BE_DEFINED_ERROR = 1492 # Variable c_int '1492'
ER_VIEW_SELECT_VARIABLE = 1351 # Variable c_int '1351'
ER_NDB_CANT_SWITCH_BINLOG_FORMAT = 1561 # Variable c_int '1561'
ER_TOO_HIGH_LEVEL_OF_NESTING_FOR_SELECT = 1473 # Variable c_int '1473'
ER_HOSTNAME = 1469 # Variable c_int '1469'
ER_DUP_FIELDNAME = 1060 # Variable c_int '1060'
ER_WRONG_MRG_TABLE = 1168 # Variable c_int '1168'
ER_TRG_ALREADY_EXISTS = 1359 # Variable c_int '1359'
ER_WRONG_OBJECT = 1347 # Variable c_int '1347'
ER_SP_CURSOR_MISMATCH = 1324 # Variable c_int '1324'
ER_NULL_COLUMN_IN_INDEX = 1121 # Variable c_int '1121'
ER_SPATIAL_CANT_HAVE_NULL = 1252 # Variable c_int '1252'
ER_INCONSISTENT_TYPE_OF_FUNCTIONS_ERROR = 1494 # Variable c_int '1494'
ER_CANT_OPEN_FILE = 1016 # Variable c_int '1016'
ER_TOO_BIG_PRECISION = 1426 # Variable c_int '1426'
ER_HASHCHK = 1000 # Variable c_int '1000'
ER_SP_UNINIT_VAR = 1311 # Variable c_int '1311'
ER_SUBPARTITION_ERROR = 1500 # Variable c_int '1500'
ER_PARTITION_FUNCTION_IS_NOT_ALLOWED = 1564 # Variable c_int '1564'
ER_UNION_TABLES_IN_DIFFERENT_DIR = 1212 # Variable c_int '1212'
ER_VIEW_PREVENT_UPDATE = 1443 # Variable c_int '1443'
ER_FPARSER_BAD_HEADER = 1341 # Variable c_int '1341'
ER_EVENT_MODIFY_QUEUE_ERROR = 1570 # Variable c_int '1570'
ER_FILSORT_ABORT = 1028 # Variable c_int '1028'
ER_NISAMCHK = 1001 # Variable c_int '1001'
ER_SP_WRONG_NAME = 1458 # Variable c_int '1458'
ER_WRONG_DB_NAME = 1102 # Variable c_int '1102'
ER_SP_LILABEL_MISMATCH = 1308 # Variable c_int '1308'
ER_MULTIPLE_DEF_CONST_IN_LIST_PART_ERROR = 1495 # Variable c_int '1495'
ER_MASTER_NET_WRITE = 1190 # Variable c_int '1190'
ER_TABLE_NOT_LOCKED = 1100 # Variable c_int '1100'
ER_NO_FORMAT_DESCRIPTION_EVENT_BEFORE_BINLOG_STATEMENT = 1609 # Variable c_int '1609'
ER_ALTER_INFO = 1088 # Variable c_int '1088'
ER_OPTION_PREVENTS_STATEMENT = 1290 # Variable c_int '1290'
ER_AUTO_CONVERT = 1246 # Variable c_int '1246'
ER_USERNAME = 1468 # Variable c_int '1468'
ER_SP_CURSOR_NOT_OPEN = 1326 # Variable c_int '1326'
ER_EVENT_DATA_TOO_LONG = 1552 # Variable c_int '1552'
ER_SLAVE_IGNORED_TABLE = 1237 # Variable c_int '1237'
ER_EVENT_CANNOT_DELETE = 1549 # Variable c_int '1549'
ER_CANT_INITIALIZE_UDF = 1123 # Variable c_int '1123'
ER_GLOBAL_VARIABLE = 1229 # Variable c_int '1229'
ER_LOCK_DEADLOCK = 1213 # Variable c_int '1213'
ER_SLAVE_INCIDENT = 1590 # Variable c_int '1590'
ER_TRG_DOES_NOT_EXIST = 1360 # Variable c_int '1360'
ER_COLUMNACCESS_DENIED_ERROR = 1143 # Variable c_int '1143'
ER_CANT_CREATE_GEOMETRY_OBJECT = 1416 # Variable c_int '1416'
ER_NON_UPDATABLE_TABLE = 1288 # Variable c_int '1288'
ER_SP_NO_RETSET = 1415 # Variable c_int '1415'
ER_SET_CONSTANTS_ONLY = 1204 # Variable c_int '1204'
ER_CANT_DROP_FIELD_OR_KEY = 1091 # Variable c_int '1091'
ER_RANGE_NOT_INCREASING_ERROR = 1493 # Variable c_int '1493'
ER_PARTITION_MERGE_ERROR = 1572 # Variable c_int '1572'
ER_SPECIFIC_ACCESS_DENIED_ERROR = 1227 # Variable c_int '1227'
ER_XA_RBTIMEOUT = 1613 # Variable c_int '1613'
ER_DUP_KEYNAME = 1061 # Variable c_int '1061'
ER_TOO_LONG_BODY = 1437 # Variable c_int '1437'
ER_ERROR_FIRST = 1000 # Variable c_int '1000'
ER_LOG_PURGE_UNKNOWN_ERR = 1379 # Variable c_int '1379'
ER_OUT_OF_SORTMEMORY = 1038 # Variable c_int '1038'
ER_ORDER_WITH_PROC = 1386 # Variable c_int '1386'
ER_UDF_EXISTS = 1125 # Variable c_int '1125'
ER_PLUGIN_IS_NOT_LOADED = 1524 # Variable c_int '1524'
ER_XAER_DUPID = 1440 # Variable c_int '1440'
ER_CANT_RENAME_LOG_TABLE = 1581 # Variable c_int '1581'
ER_ILLEGAL_VALUE_FOR_TYPE = 1367 # Variable c_int '1367'
ER_TEXTFILE_NOT_READABLE = 1085 # Variable c_int '1085'
ER_SP_NORETURN = 1320 # Variable c_int '1320'
ER_NO_CONST_EXPR_IN_RANGE_OR_LIST_ERROR = 1487 # Variable c_int '1487'
ER_CANT_CHANGE_TX_ISOLATION = 1568 # Variable c_int '1568'
ER_SP_CANT_SET_AUTOCOMMIT = 1445 # Variable c_int '1445'
ER_WRONG_FIELD_SPEC = 1063 # Variable c_int '1063'
ER_NONUPDATEABLE_COLUMN = 1348 # Variable c_int '1348'
ER_PROCACCESS_DENIED_ERROR = 1370 # Variable c_int '1370'
ER_SLAVE_THREAD = 1202 # Variable c_int '1202'
ER_MASTER_NET_READ = 1189 # Variable c_int '1189'
ER_XA_RBROLLBACK = 1402 # Variable c_int '1402'
ER_FOREIGN_SERVER_EXISTS = 1476 # Variable c_int '1476'
ER_SP_DROP_FAILED = 1306 # Variable c_int '1306'
ER_UNKNOWN_CHARACTER_SET = 1115 # Variable c_int '1115'
ER_REORG_NO_PARAM_ERROR = 1511 # Variable c_int '1511'
ER_FUNCTION_NOT_DEFINED = 1128 # Variable c_int '1128'
ER_FPARSER_ERROR_IN_PARAMETER = 1343 # Variable c_int '1343'
ER_TABLE_CANT_HANDLE_FT = 1214 # Variable c_int '1214'
ER_UNKNOWN_ERROR = 1105 # Variable c_int '1105'
ER_ADD_PARTITION_NO_NEW_PARTITION = 1514 # Variable c_int '1514'
ER_WARN_ALLOWED_PACKET_OVERFLOWED = 1301 # Variable c_int '1301'
ER_SELECT_REDUCED = 1249 # Variable c_int '1249'
ER_TRG_IN_WRONG_SCHEMA = 1435 # Variable c_int '1435'
ER_WARN_DATA_OUT_OF_RANGE = 1264 # Variable c_int '1264'
ER_UNSUPPORTED_EXTENSION = 1112 # Variable c_int '1112'
ER_INSERT_INFO = 1092 # Variable c_int '1092'
ER_WARN_DEPRECATED_SYNTAX_WITH_VER = 1554 # Variable c_int '1554'
ER_ACCESS_DENIED_ERROR = 1045 # Variable c_int '1045'
ER_OUT_OF_RESOURCES = 1041 # Variable c_int '1041'
ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG = 1336 # Variable c_int '1336'
ER_DB_DROP_EXISTS = 1008 # Variable c_int '1008'
ER_OPEN_AS_READONLY = 1036 # Variable c_int '1036'
ER_COLLATION_CHARSET_MISMATCH = 1253 # Variable c_int '1253'
ER_LOG_PURGE_NO_FILE = 1612 # Variable c_int '1612'
ER_MISSING_SKIP_SLAVE = 1278 # Variable c_int '1278'
ER_KEY_PART_0 = 1391 # Variable c_int '1391'
ER_XAER_RMERR = 1401 # Variable c_int '1401'
ER_NEED_REPREPARE = 1615 # Variable c_int '1615'
ER_FLUSH_MASTER_BINLOG_CLOSED = 1186 # Variable c_int '1186'
ER_SP_BADSTATEMENT = 1314 # Variable c_int '1314'
ER_TRG_NO_DEFINER = 1454 # Variable c_int '1454'
ER_TOO_LONG_KEY = 1071 # Variable c_int '1071'
ER_NO_SUCH_USER = 1449 # Variable c_int '1449'
ER_DIFF_GROUPS_PROC = 1384 # Variable c_int '1384'
ER_EVENT_DOES_NOT_EXIST = 1539 # Variable c_int '1539'
ER_NONUNIQ_TABLE = 1066 # Variable c_int '1066'
ER_WRONG_NAME_FOR_CATALOG = 1281 # Variable c_int '1281'
ER_QUERY_ON_MASTER = 1219 # Variable c_int '1219'
ER_NO_SUCH_THREAD = 1094 # Variable c_int '1094'
ER_BLOBS_AND_NO_TERMINATED = 1084 # Variable c_int '1084'
ER_SP_GOTO_IN_HNDLR = 1358 # Variable c_int '1358'
ER_CON_COUNT_ERROR = 1040 # Variable c_int '1040'
ER_CUT_VALUE_GROUP_CONCAT = 1260 # Variable c_int '1260'
ER_CRASHED_ON_USAGE = 1194 # Variable c_int '1194'
ER_WRONG_STRING_LENGTH = 1470 # Variable c_int '1470'
ER_FORCING_CLOSE = 1080 # Variable c_int '1080'
ER_WRONG_USAGE = 1221 # Variable c_int '1221'
ER_EVENT_INTERVAL_NOT_POSITIVE_OR_TOO_BIG = 1542 # Variable c_int '1542'
ER_PARSE_ERROR = 1064 # Variable c_int '1064'
ER_DB_DROP_RMDIR = 1010 # Variable c_int '1010'
ER_SIZE_OVERFLOW_ERROR = 1532 # Variable c_int '1532'
ER_PS_NO_RECURSION = 1444 # Variable c_int '1444'
ER_FPARSER_EOF_IN_COMMENT = 1342 # Variable c_int '1342'
ER_DROP_INDEX_FK = 1553 # Variable c_int '1553'
ER_VIEW_INVALID = 1356 # Variable c_int '1356'
ER_XAER_NOTA = 1397 # Variable c_int '1397'
ER_PARTITION_NO_TEMPORARY = 1562 # Variable c_int '1562'
ER_EVENT_CANNOT_ALTER_IN_THE_PAST = 1589 # Variable c_int '1589'
ER_UPDATE_INFO = 1134 # Variable c_int '1134'
ER_TOO_MANY_PARTITIONS_ERROR = 1499 # Variable c_int '1499'
ER_UNKNOWN_SYSTEM_VARIABLE = 1193 # Variable c_int '1193'
ER_TABLESPACE_AUTO_EXTEND_ERROR = 1530 # Variable c_int '1530'
ER_STACK_OVERRUN = 1119 # Variable c_int '1119'
ER_SLAVE_RELAY_LOG_WRITE_FAILURE = 1595 # Variable c_int '1595'
ER_HOST_NOT_PRIVILEGED = 1130 # Variable c_int '1130'
ER_CANT_CREATE_DB = 1006 # Variable c_int '1006'
ER_PARTITION_WRONG_NO_PART_ERROR = 1484 # Variable c_int '1484'
ER_CANNOT_LOAD_FROM_TABLE = 1548 # Variable c_int '1548'
ER_CONFLICTING_DECLARATIONS = 1302 # Variable c_int '1302'
ER_UPDATE_LOG_DEPRECATED_IGNORED = 1315 # Variable c_int '1315'
ER_BAD_SLAVE_UNTIL_COND = 1277 # Variable c_int '1277'
ER_NO_RAID_COMPILED = 1174 # Variable c_int '1174'
ER_TABLE_MUST_HAVE_COLUMNS = 1113 # Variable c_int '1113'
ER_VIEW_OTHER_USER = 1448 # Variable c_int '1448'
ER_READY = 1076 # Variable c_int '1076'
ER_SP_WRONG_NO_OF_ARGS = 1318 # Variable c_int '1318'
ER_EVENT_SAME_NAME = 1551 # Variable c_int '1551'
ER_UDF_NO_PATHS = 1124 # Variable c_int '1124'
ER_FSEEK_FAIL = 1376 # Variable c_int '1376'
ER_INVALID_GROUP_FUNC_USE = 1111 # Variable c_int '1111'
ER_CANT_CREATE_TABLE = 1005 # Variable c_int '1005'
ER_SP_BAD_SQLSTATE = 1407 # Variable c_int '1407'
ER_LOAD_DATA_INVALID_COLUMN = 1611 # Variable c_int '1611'
ER_CANT_GET_WD = 1014 # Variable c_int '1014'
ER_UNIQUE_KEY_NEED_ALL_FIELDS_IN_PF = 1503 # Variable c_int '1503'
ER_ERROR_ON_CLOSE = 1023 # Variable c_int '1023'
ER_ERROR_DURING_CHECKPOINT = 1183 # Variable c_int '1183'
ER_TRG_CORRUPTED_FILE = 1602 # Variable c_int '1602'
ER_SP_PROC_TABLE_CORRUPT = 1457 # Variable c_int '1457'
ER_SLAVE_AMBIGOUS_EXEC_MODE = 1608 # Variable c_int '1608'
ER_QUERY_INTERRUPTED = 1317 # Variable c_int '1317'
ER_TRG_CANT_CHANGE_ROW = 1362 # Variable c_int '1362'
ER_QUERY_ON_FOREIGN_DATA_SOURCE = 1430 # Variable c_int '1430'
ER_TRUNCATED_WRONG_VALUE_FOR_FIELD = 1366 # Variable c_int '1366'
ER_VIEW_SELECT_TMPTABLE = 1352 # Variable c_int '1352'
ER_NULL_IN_VALUES_LESS_THAN = 1566 # Variable c_int '1566'
ER_ERROR_DURING_FLUSH_LOGS = 1182 # Variable c_int '1182'
ER_BINLOG_UNSAFE_STATEMENT = 1592 # Variable c_int '1592'
ER_ERROR_ON_WRITE = 1026 # Variable c_int '1026'
ER_BINLOG_UNSAFE_ROUTINE = 1418 # Variable c_int '1418'
ER_WARN_FIELD_RESOLVED = 1276 # Variable c_int '1276'
ER_DUP_ENTRY_AUTOINCREMENT_CASE = 1569 # Variable c_int '1569'
ER_LOCK_WAIT_TIMEOUT = 1205 # Variable c_int '1205'
ER_ZLIB_Z_DATA_ERROR = 1259 # Variable c_int '1259'
ER_WARN_TOO_MANY_RECORDS = 1262 # Variable c_int '1262'
ER_CREATE_FILEGROUP_FAILED = 1528 # Variable c_int '1528'
ER_FPARSER_TOO_BIG_FILE = 1340 # Variable c_int '1340'
ER_IPSOCK_ERROR = 1081 # Variable c_int '1081'
ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE = 1558 # Variable c_int '1558'
ER_UNKNOWN_KEY_CACHE = 1284 # Variable c_int '1284'
ER_FOREIGN_DATA_STRING_INVALID = 1433 # Variable c_int '1433'
ER_CANT_UPDATE_WITH_READLOCK = 1223 # Variable c_int '1223'
ER_SP_ALREADY_EXISTS = 1304 # Variable c_int '1304'
ER_DROP_PARTITION_NON_EXISTENT = 1507 # Variable c_int '1507'
ER_SP_BADRETURN = 1313 # Variable c_int '1313'
ER_SLAVE_IGNORED_SSL_PARAMS = 1274 # Variable c_int '1274'
ER_DELAYED_INSERT_TABLE_LOCKED = 1165 # Variable c_int '1165'
ER_DIVISION_BY_ZERO = 1365 # Variable c_int '1365'
ER_FEATURE_DISABLED = 1289 # Variable c_int '1289'
ER_SP_DUP_COND = 1332 # Variable c_int '1332'
ER_CANT_CREATE_SROUTINE = 1607 # Variable c_int '1607'
ER_BAD_DB_ERROR = 1049 # Variable c_int '1049'
ER_WRONG_SIZE_NUMBER = 1531 # Variable c_int '1531'
ER_PARTITION_ENTRY_ERROR = 1496 # Variable c_int '1496'
ER_BLOB_USED_AS_KEY = 1073 # Variable c_int '1073'
ER_TRG_ON_VIEW_OR_TEMP_TABLE = 1361 # Variable c_int '1361'
ER_UNKNOWN_STORAGE_ENGINE = 1286 # Variable c_int '1286'
ER_OPERAND_COLUMNS = 1241 # Variable c_int '1241'
ER_FOREIGN_DUPLICATE_KEY = 1557 # Variable c_int '1557'
ER_DROP_LAST_PARTITION = 1508 # Variable c_int '1508'
ER_KEY_DOES_NOT_EXITS = 1176 # Variable c_int '1176'
ER_VIEW_SELECT_CLAUSE = 1350 # Variable c_int '1350'
ER_USER_LIMIT_REACHED = 1226 # Variable c_int '1226'
ER_CANT_AGGREGATE_NCOLLATIONS = 1271 # Variable c_int '1271'
ER_PROC_AUTO_REVOKE_FAIL = 1405 # Variable c_int '1405'
ER_DBACCESS_DENIED_ERROR = 1044 # Variable c_int '1044'
ER_TOO_BIG_DISPLAYWIDTH = 1439 # Variable c_int '1439'
ER_CANT_CREATE_HANDLER_FILE = 1501 # Variable c_int '1501'
ER_CANT_AGGREGATE_2COLLATIONS = 1267 # Variable c_int '1267'
ER_SLAVE_WAS_NOT_RUNNING = 1255 # Variable c_int '1255'
ER_CANT_CREATE_THREAD = 1135 # Variable c_int '1135'
ER_NO_DEFAULT_FOR_FIELD = 1364 # Variable c_int '1364'
ER_MIX_HANDLER_ERROR = 1497 # Variable c_int '1497'
ER_FPARSER_EOF_IN_UNKNOWN_PARAMETER = 1344 # Variable c_int '1344'
ER_LIMITED_PART_RANGE = 1523 # Variable c_int '1523'
ER_SP_CURSOR_AFTER_HANDLER = 1338 # Variable c_int '1338'
ER_LOCK_OR_ACTIVE_TRANSACTION = 1192 # Variable c_int '1192'
ER_WRONG_OUTER_JOIN = 1120 # Variable c_int '1120'
ER_SP_STORE_FAILED = 1307 # Variable c_int '1307'
ER_BINLOG_PURGE_EMFILE = 1587 # Variable c_int '1587'
ER_WRONG_ARGUMENTS = 1210 # Variable c_int '1210'
ER_UNKNOWN_STMT_HANDLER = 1243 # Variable c_int '1243'
ER_NO_TABLES_USED = 1096 # Variable c_int '1096'
ER_WARN_DEPRECATED_SYNTAX = 1287 # Variable c_int '1287'
ER_TOO_BIG_SELECT = 1104 # Variable c_int '1104'
ER_NOT_KEYFILE = 1034 # Variable c_int '1034'
ER_NO_FILE_MAPPING = 1388 # Variable c_int '1388'
ER_WRONG_VALUE = 1525 # Variable c_int '1525'
ER_ERROR_DURING_COMMIT = 1180 # Variable c_int '1180'
ER_HOST_IS_BLOCKED = 1129 # Variable c_int '1129'
ER_BINLOG_PURGE_FATAL_ERR = 1377 # Variable c_int '1377'
ER_VIEW_WRONG_LIST = 1353 # Variable c_int '1353'
__all__ = ['ER_DROP_FILEGROUP_FAILED', 'ER_EVENT_DROP_FAILED',
           'ER_VIEW_CHECKSUM', 'ER_BAD_FIELD_ERROR',
           'ER_FT_MATCHING_KEY_NOT_FOUND', 'ER_WRONG_KEY_COLUMN',
           'ER_VAR_CANT_BE_READ',
           'ER_UNIQUE_KEY_NEED_ALL_FIELDS_IN_PF',
           'ER_CANT_USE_OPTION_HERE', 'ER_NATIVE_FCT_NAME_COLLISION',
           'ER_MASTER_INFO', 'ER_NET_PACKETS_OUT_OF_ORDER',
           'ER_RECORD_FILE_FULL', 'ER_SLAVE_RELAY_LOG_WRITE_FAILURE',
           'ER_IO_ERR_LOG_INDEX_READ', 'ER_TOO_BIG_SET',
           'ER_NO_PARTITION_FOR_GIVEN_VALUE_SILENT',
           'ER_ERROR_WHEN_EXECUTING_COMMAND', 'ER_SP_CASE_NOT_FOUND',
           'ER_ERROR_ON_RENAME', 'ER_NON_INSERTABLE_TABLE',
           'ER_NO_DEFAULT_FOR_VIEW_FIELD', 'ER_STARTUP',
           'ER_SP_RECURSION_LIMIT', 'ER_WRONG_PARTITION_NAME',
           'ER_PROC_AUTO_GRANT_FAIL', 'ER_FORBID_SCHEMA_CHANGE',
           'ER_SP_WRONG_NO_OF_FETCH_ARGS', 'ER_NO_SUCH_TABLE',
           'ER_WARNING_NOT_COMPLETE_ROLLBACK', 'ER_SUBQUERY_NO_1_ROW',
           'ER_EVENT_STORE_FAILED', 'ER_WRONG_FIELD_WITH_GROUP',
           'ER_CHECK_NOT_IMPLEMENTED', 'ER_CANT_WRITE_LOCK_LOG_TABLE',
           'ER_BLOB_CANT_HAVE_DEFAULT', 'ER_ADMIN_WRONG_MRG_TABLE',
           'ER_NO_TRIGGERS_ON_SYSTEM_SCHEMA',
           'ER_NULL_IN_VALUES_LESS_THAN',
           'ER_NO_PARTITION_FOR_GIVEN_VALUE',
           'ER_NONEXISTING_TABLE_GRANT', 'ER_WRONG_MAGIC',
           'ER_TOO_BIG_FIELDLENGTH',
           'ER_SPECIFIC_ACCESS_DENIED_ERROR', 'ER_VIEW_CHECK_FAILED',
           'ER_BLOB_FIELD_IN_PART_FUNC_ERROR', 'ER_MULTIPLE_PRI_KEY',
           'ER_SLAVE_MUST_STOP', 'ER_ROW_IS_REFERENCED_2',
           'ER_DELAYED_NOT_SUPPORTED', 'ER_GET_TEMPORARY_ERRMSG',
           'ER_CON_COUNT_ERROR', 'ER_TRG_NO_CREATION_CTX',
           'ER_NET_READ_INTERRUPTED', 'ER_TOO_LONG_BODY',
           'ER_DB_DROP_DELETE', 'ER_WSAS_FAILED',
           'ER_VIEW_NONUPD_CHECK', 'ER_REQUIRES_PRIMARY_KEY',
           'ER_RELAY_LOG_INIT', 'ER_LOCK_TABLE_FULL',
           'ER_MAX_PREPARED_STMT_COUNT_REACHED',
           'ER_DB_CREATE_EXISTS', 'ER_CORRUPT_HELP_DB',
           'ER_TOO_MANY_DELAYED_THREADS', 'ER_SP_LABEL_REDEFINE',
           'ER_ILLEGAL_REFERENCE', 'ER_ERROR_LAST',
           'ER_HANDSHAKE_ERROR', 'ER_OPEN_AS_READONLY',
           'ER_SP_DUP_HANDLER', 'ER_WRONG_VALUE_COUNT',
           'ER_READ_ONLY_TRANSACTION', 'ER_CANT_ACTIVATE_LOG',
           'ER_MASTER', 'ER_ONLY_ON_RANGE_LIST_PARTITION',
           'ER_TRUNCATED_WRONG_VALUE', 'ER_NO_DEFAULT',
           'ER_NOT_SUPPORTED_AUTH_MODE', 'ER_DROP_LAST_PARTITION',
           'ER_DISK_FULL', 'ER_LIST_OF_FIELDS_ONLY_IN_HASH_ERROR',
           'ER_EVENT_COMPILE_ERROR', 'ER_FORM_NOT_FOUND',
           'ER_SP_FETCH_NO_DATA', 'ER_CANT_FIND_DL_ENTRY',
           'ER_WARN_USING_OTHER_HANDLER', 'ER_LOG_IN_USE',
           'ER_REORG_HASH_ONLY_ON_SAME_NO', 'ER_SP_DOES_NOT_EXIST',
           'ER_PASSWORD_ANONYMOUS_USER', 'ER_VIEW_MULTIUPDATE',
           'ER_SP_NO_RECURSION', 'ER_PARTITION_SUBPARTITION_ERROR',
           'ER_VIEW_SELECT_DERIVED', 'ER_VIEW_SELECT_TMPTABLE',
           'ER_ALTER_FILEGROUP_FAILED', 'ER_IPSOCK_ERROR',
           'ER_TRG_CANT_OPEN_TABLE', 'ER_CANT_REMOVE_ALL_FIELDS',
           'ER_WRONG_VALUE_FOR_TYPE', 'ER_FOREIGN_KEY_ON_PARTITIONED',
           'ER_BLOB_KEY_WITHOUT_LENGTH', 'ER_VIEW_NO_EXPLAIN',
           'ER_WARN_VIEW_WITHOUT_KEY', 'ER_PRIMARY_CANT_HAVE_NULL',
           'ER_NO_GROUP_FOR_PROC',
           'ER_TABLE_CANT_HANDLE_AUTO_INCREMENT', 'ER_KEY_NOT_FOUND',
           'ER_WARN_QC_RESIZE', 'ER_INVALID_CHARACTER_STRING',
           'ER_NOT_FORM_FILE', 'ER_INCORRECT_GLOBAL_LOCAL_VAR',
           'ER_TOO_MANY_USER_CONNECTIONS',
           'ER_WRONG_PARAMCOUNT_TO_PROCEDURE', 'ER_KILL_DENIED_ERROR',
           'ER_TRANS_CACHE_FULL', 'ER_FOREIGN_SERVER_DOESNT_EXIST',
           'ER_TOO_BIG_SCALE', 'ER_BINLOG_LOGGING_IMPOSSIBLE',
           'ER_YES', 'ER_CHECK_NO_SUCH_TABLE',
           'ER_SLAVE_CORRUPT_EVENT', 'ER_BASE64_DECODE_ERROR',
           'ER_PARTITION_WRONG_VALUES_ERROR',
           'ER_SP_NO_RECURSIVE_CREATE', 'ER_SLAVE_FATAL_ERROR',
           'ER_TOO_MANY_FIELDS', 'ER_ERROR_ON_CLOSE',
           'ER_ZLIB_Z_MEM_ERROR', 'ER_XAER_RMFAIL',
           'ER_MALFORMED_DEFINER', 'ER_SP_NOT_VAR_ARG',
           'ER_CONST_EXPR_IN_PARTITION_FUNC_ERROR',
           'ER_WRONG_GROUP_FIELD', 'ER_TABLE_CANT_HANDLE_SPKEYS',
           'ER_UPDATE_WITHOUT_KEY_IN_SAFE_MODE',
           'ER_TOO_BIG_FOR_UNCOMPRESS', 'ER_PART_STATE_ERROR',
           'ER_FAILED_ROUTINE_BREAK_BINLOG', 'ER_TRG_CORRUPTED_FILE',
           'ER_REVOKE_GRANTS', 'ER_LOAD_FROM_FIXED_SIZE_ROWS_TO_VAR',
           'ER_SP_CURSOR_ALREADY_OPEN', 'ER_DROP_USER',
           'ER_NET_WRITE_INTERRUPTED', 'ER_SP_NO_DROP_SP',
           'ER_RBR_NOT_AVAILABLE', 'ER_WRONG_COLUMN_NAME',
           'ER_WARN_HOSTNAME_WONT_WORK',
           'ER_CANT_UPDATE_USED_TABLE_IN_SF_OR_TRG',
           'ER_TRG_INVALID_CREATION_CTX', 'ER_UNKNOWN_TIME_ZONE',
           'ER_SP_BAD_CURSOR_QUERY',
           'ER_FOREIGN_DATA_STRING_INVALID_CANT_CREATE',
           'ER_ONLY_INTEGERS_ALLOWED', 'ER_CRASHED_ON_REPAIR',
           'ER_SP_BAD_VAR_SHADOW', 'ER_NET_ERROR_ON_WRITE',
           'ER_ILLEGAL_HA_CREATE_OPTION',
           'ER_DELAYED_CANT_CHANGE_LOCK', 'ER_NO_BINARY_LOGGING',
           'ER_DUP_ENTRY_WITH_KEY_NAME', 'ER_GET_ERRMSG',
           'ER_TOO_MUCH_AUTO_TIMESTAMP_COLS',
           'ER_REORG_PARTITION_NOT_EXIST', 'ER_FRM_UNKNOWN_TYPE',
           'ER_PARTITION_CONST_DOMAIN_ERROR',
           'ER_TABLEACCESS_DENIED_ERROR', 'ER_ILLEGAL_HA',
           'ER_WRONG_VALUE_FOR_VAR',
           'ER_QUERY_ON_FOREIGN_DATA_SOURCE', 'ER_PASSWD_LENGTH',
           'ER_SP_SUBSELECT_NYI', 'ER_NOT_SUPPORTED_YET',
           'ER_WARN_CANT_DROP_DEFAULT_KEYCACHE',
           'ER_COL_COUNT_DOESNT_MATCH_CORRUPTED',
           'ER_UPDATE_TABLE_USED', 'ER_UNTIL_COND_IGNORED',
           'ER_CANNOT_USER', 'ER_KEY_REF_DO_NOT_MATCH_TABLE_REF',
           'ER_PS_MANY_PARAM', 'ER_PARTITION_MAXVALUE_ERROR',
           'ER_CANT_DELETE_FILE', 'ER_STMT_HAS_NO_OPEN_CURSOR',
           'ER_TOO_MANY_ROWS', 'ER_LOAD_INFO',
           'ER_CANT_CREATE_THREAD',
           'ER_WRONG_PARAMETERS_TO_STORED_FCT',
           'ER_FOREIGN_DATA_SOURCE_DOESNT_EXIST',
           'ER_TABLE_CANT_HANDLE_FT', 'ER_VIEW_NO_INSERT_FIELD_LIST',
           'ER_SLAVE_MASTER_COM_FAILURE', 'ER_ABORTING_CONNECTION',
           'ER_DDL_LOG_ERROR', 'ER_BINLOG_ROW_RBR_TO_SBR',
           'ER_FILE_EXISTS_ERROR', 'ER_REORG_OUTSIDE_RANGE',
           'ER_EMPTY_QUERY', 'ER_SP_LABEL_MISMATCH',
           'ER_ILLEGAL_GRANT_FOR_TABLE', 'ER_REGEXP_ERROR',
           'ER_LOGGING_PROHIBIT_CHANGING_OF',
           'ER_WRONG_FIELD_TERMINATORS', 'ER_NO_PARTS_ERROR',
           'ER_RELAY_LOG_FAIL', 'ER_BINLOG_ROW_LOGGING_FAILED',
           'ER_CANT_DO_THIS_DURING_AN_TRANSACTION',
           'ER_TABLE_NEEDS_UPGRADE', 'ER_RESERVED_SYNTAX',
           'ER_INVALID_ON_UPDATE', 'ER_WARN_NULL_TO_NOTNULL',
           'ER_XA_RBDEADLOCK', 'ER_EVENT_ALREADY_EXISTS',
           'ER_CREATE_DB_WITH_READ_LOCK', 'ER_SP_DUP_CURS',
           'ER_DUPLICATED_VALUE_IN_TYPE', 'ER_DUP_UNIQUE',
           'ER_UNKNOWN_TABLE', 'ER_TOO_MANY_KEY_PARTS',
           'ER_FILE_USED', 'ER_SP_VARCOND_AFTER_CURSHNDLR',
           'ER_LOCAL_VARIABLE', 'ER_BINLOG_PURGE_PROHIBITED',
           'ER_SP_CANT_ALTER', 'ER_PARTITION_SUBPART_MIX_ERROR',
           'ER_CONNECT_TO_FOREIGN_DATA_SOURCE',
           'ER_WRONG_PARAMETERS_TO_PROCEDURE', 'ER_UNSUPPORTED_PS',
           'ER_INDEX_REBUILD', 'ER_PASSWORD_NOT_ALLOWED',
           'ER_BAD_TABLE_ERROR', 'ER_WRONG_PARAMETERS_TO_NATIVE_FCT',
           'ER_NET_PACKET_TOO_LARGE', 'ER_NAME_BECOMES_EMPTY',
           'ER_CANT_GET_STAT', 'ER_BAD_SLAVE',
           'ER_EVENT_EXEC_TIME_IN_THE_PAST',
           'ER_WRONG_VALUE_COUNT_ON_ROW', 'ER_NET_READ_ERROR',
           'ER_AMBIGUOUS_FIELD_TERM',
           'ER_CONSECUTIVE_REORG_PARTITIONS',
           'ER_VARIABLE_IS_NOT_STRUCT', 'WARN_DATA_TRUNCATED',
           'ER_WARN_INVALID_TIMESTAMP',
           'ER_CANT_CREATE_USER_WITH_GRANT',
           'ER_TRG_NO_SUCH_ROW_IN_TRG',
           'ER_PARTITION_MGMT_ON_NONPARTITIONED',
           'ER_COALESCE_ONLY_ON_HASH_PARTITION',
           'ER_DATETIME_FUNCTION_OVERFLOW', 'ER_REMOVED_SPACES',
           'ER_NONEXISTING_GRANT', 'ER_ADD_PARTITION_SUBPART_ERROR',
           'ER_NO_REFERENCED_ROW_2',
           'ER_SLAVE_RELAY_LOG_READ_FAILURE', 'ER_NO_BINLOG_ERROR',
           'ER_GOT_SIGNAL', 'ER_SHUTDOWN_COMPLETE',
           'ER_WARN_DATA_OUT_OF_RANGE', 'ER_WRONG_TYPE_FOR_VAR',
           'ER_DUP_ARGUMENT', 'ER_SP_NORETURNEND', 'ER_CANT_LOCK',
           'ER_TABLE_DEF_CHANGED', 'ER_FILE_NOT_FOUND',
           'ER_SYNTAX_ERROR', 'ER_WARN_TOO_FEW_RECORDS',
           'ER_AUTOINC_READ_FAILED', 'ER_TOO_LONG_IDENT',
           'ER_FEATURE_DISABLED', 'ER_SP_COND_MISMATCH',
           'ER_SLAVE_WAS_RUNNING', 'ER_ERROR_DURING_ROLLBACK',
           'ER_MIXING_NOT_ALLOWED', 'ER_TABLE_NOT_LOCKED_FOR_WRITE',
           'ER_OLD_KEYFILE', 'ER_BINLOG_ROW_WRONG_TABLE_DEF',
           'ER_CANT_AGGREGATE_3COLLATIONS', 'ER_SP_BAD_CURSOR_SELECT',
           'ER_NON_GROUPING_FIELD_USED', 'ER_DROP_DB_WITH_READ_LOCK',
           'ER_SERVER_SHUTDOWN', 'ER_M_BIGGER_THAN_D',
           'ER_TOO_LONG_STRING', 'ER_OLD_FILE_FORMAT',
           'ER_EVENT_ENDS_BEFORE_STARTS',
           'ER_COALESCE_PARTITION_NO_PARTITION',
           'ER_NOT_ALLOWED_COMMAND', 'ER_VIEW_INVALID_CREATION_CTX',
           'ER_UNSUPORTED_LOG_ENGINE',
           'ER_MIX_OF_GROUP_FUNC_AND_FIELDS', 'ER_DUP_KEY',
           'ER_UNKNOWN_COM_ERROR', 'ER_SP_DUP_VAR',
           'ER_TEMP_TABLE_PREVENTS_SWITCH_OUT_OF_RBR',
           'ER_SLAVE_NOT_RUNNING',
           'ER_BINLOG_CREATE_ROUTINE_NEED_SUPER',
           'ER_KEY_COLUMN_DOES_NOT_EXITS', 'ER_WRONG_SUB_KEY',
           'ER_UNKNOWN_COLLATION', 'ER_WARN_VIEW_MERGE',
           'ER_VIEW_NO_CREATION_CTX',
           'ER_NO_PERMISSION_TO_CREATE_USER', 'ER_TOO_MANY_TABLES',
           'ER_STACK_OVERRUN_NEED_MORE', 'ER_SP_DUP_PARAM',
           'ER_EVENT_SET_VAR_ERROR', 'ER_WRONG_LOCK_OF_SYSTEM_TABLE',
           'ER_TABLE_CANT_HANDLE_BLOB', 'ER_UNKNOWN_PROCEDURE',
           'ER_UNEXPECTED_EOF', 'ER_ROW_IS_REFERENCED',
           'ER_CANT_REOPEN_TABLE', 'ER_EVENT_OPEN_TABLE_FAILED',
           'ER_CANT_UPDATE_WITH_READLOCK',
           'ER_TABLENAME_NOT_ALLOWED_HERE', 'ER_SP_ALREADY_EXISTS',
           'ER_FOREIGN_SERVER_EXISTS', 'ER_PASSWORD_NO_MATCH',
           'ER_XAER_INVAL', 'ER_NO_REFERENCED_ROW',
           'ER_SERVER_IS_IN_SECURE_AUTH_MODE', 'ER_NET_FCNTL_ERROR',
           'ER_SAME_NAME_PARTITION', 'ER_PARTITION_NOT_DEFINED_ERROR',
           'ER_SP_BADRETURN', 'ER_WRONG_NUMBER_OF_COLUMNS_IN_SELECT',
           'ER_QUERY_INTERRUPTED', 'ER_GET_ERRNO',
           'ER_EVENT_CANNOT_CREATE_IN_THE_PAST', 'ER_EVENTS_DB_ERROR',
           'ER_CANT_CREATE_FILE',
           'ER_STORED_FUNCTION_PREVENTS_SWITCH_BINLOG_FORMAT',
           'ER_CONNECT_TO_MASTER', 'ER_CANT_OPEN_LIBRARY',
           'ER_DATA_TOO_LONG', 'ER_ZLIB_Z_BUF_ERROR',
           'ER_SLAVE_CREATE_EVENT_FAILURE', 'ER_BAD_LOG_STATEMENT',
           'ER_NET_READ_ERROR_FROM_PIPE', 'ER_HOST_NOT_PRIVILEGED',
           'ER_FIELD_SPECIFIED_TWICE',
           'ER_EVENT_NEITHER_M_EXPR_NOR_M_AT', 'ER_INVALID_DEFAULT',
           'ER_FILEGROUP_OPTION_ONLY_ONCE', 'ER_NON_UNIQ_ERROR',
           'ER_BAD_FT_COLUMN', 'ER_MASTER_FATAL_ERROR_READING_BINLOG',
           'ER_NET_UNCOMPRESS_ERROR', 'ER_TOO_MANY_KEYS',
           'ER_WRONG_FK_DEF', 'ER_OUTOFMEMORY', 'ER_CHECKREAD',
           'ER_SP_BADSELECT', 'ER_CANT_READ_DIR',
           'ER_EVENT_CANT_ALTER', 'ER_GRANT_WRONG_HOST_OR_USER',
           'ER_SP_UNDECLARED_VAR', 'ER_FIELD_NOT_FOUND_PART_ERROR',
           'ER_PARTITION_FUNC_NOT_ALLOWED_ERROR',
           'ER_SR_INVALID_CREATION_CTX', 'ER_VIEW_DELETE_MERGE_VIEW',
           'ER_UPDATE_LOG_DEPRECATED_TRANSLATED',
           'ER_CANT_CREATE_FEDERATED_TABLE', 'ER_CANNOT_ADD_FOREIGN',
           'ER_CANT_FIND_SYSTEM_REC', 'ER_EVENT_RECURSION_FORBIDDEN',
           'ER_VIEW_FRM_NO_USER',
           'ER_COMMIT_NOT_ALLOWED_IN_SF_OR_TRG',
           'ER_DUMP_NOT_IMPLEMENTED', 'ER_WRONG_TABLE_NAME',
           'ER_CANT_FIND_UDF', 'ER_NORMAL_SHUTDOWN',
           'ER_INCONSISTENT_PARTITION_INFO_ERROR', 'ER_NO_SUCH_INDEX',
           'ER_TOO_BIG_ROWSIZE', 'ER_NO_UNIQUE_LOGFILE',
           'ER_CYCLIC_REFERENCE',
           'ER_PARTITIONS_MUST_BE_DEFINED_ERROR',
           'ER_VIEW_SELECT_VARIABLE',
           'ER_NDB_CANT_SWITCH_BINLOG_FORMAT',
           'ER_TOO_HIGH_LEVEL_OF_NESTING_FOR_SELECT', 'ER_HOSTNAME',
           'ER_DUP_FIELDNAME', 'ER_WRONG_MRG_TABLE',
           'ER_TRG_ALREADY_EXISTS', 'ER_WRONG_OBJECT',
           'ER_SP_CURSOR_MISMATCH', 'ER_NULL_COLUMN_IN_INDEX',
           'ER_SPATIAL_CANT_HAVE_NULL',
           'ER_INCONSISTENT_TYPE_OF_FUNCTIONS_ERROR',
           'ER_CANT_OPEN_FILE', 'ER_TOO_BIG_PRECISION', 'ER_HASHCHK',
           'ER_SP_UNINIT_VAR', 'ER_EXEC_STMT_WITH_OPEN_CURSOR',
           'ER_PARTITION_FUNCTION_IS_NOT_ALLOWED',
           'ER_UNION_TABLES_IN_DIFFERENT_DIR',
           'ER_VIEW_PREVENT_UPDATE', 'ER_FPARSER_BAD_HEADER',
           'ER_EVENT_MODIFY_QUEUE_ERROR', 'ER_FILSORT_ABORT',
           'ER_SP_WRONG_NAME', 'ER_WRONG_DB_NAME',
           'ER_SP_LILABEL_MISMATCH',
           'ER_MULTIPLE_DEF_CONST_IN_LIST_PART_ERROR',
           'ER_MASTER_NET_WRITE', 'ER_TABLE_NOT_LOCKED',
           'ER_NO_FORMAT_DESCRIPTION_EVENT_BEFORE_BINLOG_STATEMENT',
           'ER_ALTER_INFO', 'ER_OPTION_PREVENTS_STATEMENT',
           'ER_AUTO_CONVERT', 'ER_INVALID_USE_OF_NULL',
           'ER_SP_CURSOR_NOT_OPEN', 'ER_EVENT_DATA_TOO_LONG',
           'ER_SLAVE_IGNORED_TABLE', 'ER_EVENT_CANNOT_DELETE',
           'ER_CANT_INITIALIZE_UDF', 'ER_GLOBAL_VARIABLE',
           'ER_LOCK_DEADLOCK', 'ER_SLAVE_INCIDENT',
           'ER_TRG_DOES_NOT_EXIST', 'ER_COLUMNACCESS_DENIED_ERROR',
           'ER_CANT_CREATE_GEOMETRY_OBJECT', 'ER_NON_UPDATABLE_TABLE',
           'ER_SP_NO_RETSET', 'ER_SET_CONSTANTS_ONLY',
           'ER_CANT_DROP_FIELD_OR_KEY',
           'ER_RANGE_NOT_INCREASING_ERROR',
           'ER_PARTITION_MERGE_ERROR', 'ER_DERIVED_MUST_HAVE_ALIAS',
           'ER_XA_RBTIMEOUT', 'ER_DUP_KEYNAME', 'ER_WRONG_AUTO_KEY',
           'ER_ERROR_FIRST', 'ER_LOG_PURGE_UNKNOWN_ERR',
           'ER_OUT_OF_SORTMEMORY', 'ER_ORDER_WITH_PROC',
           'ER_UDF_EXISTS', 'ER_PLUGIN_IS_NOT_LOADED',
           'ER_XAER_DUPID', 'ER_ILLEGAL_VALUE_FOR_TYPE',
           'ER_TEXTFILE_NOT_READABLE', 'ER_SP_NORETURN',
           'ER_NO_CONST_EXPR_IN_RANGE_OR_LIST_ERROR',
           'ER_CANT_CHANGE_TX_ISOLATION',
           'ER_FLUSH_MASTER_BINLOG_CLOSED', 'ER_WRONG_FIELD_SPEC',
           'ER_NONUPDATEABLE_COLUMN', 'ER_PROCACCESS_DENIED_ERROR',
           'ER_MASTER_NET_READ', 'ER_XA_RBROLLBACK',
           'ER_ERROR_ON_READ', 'ER_SP_DROP_FAILED',
           'ER_UNKNOWN_CHARACTER_SET', 'ER_REORG_NO_PARAM_ERROR',
           'ER_FUNCTION_NOT_DEFINED', 'ER_FPARSER_ERROR_IN_PARAMETER',
           'ER_CANT_LOCK_LOG_TABLE', 'ER_UNKNOWN_ERROR',
           'ER_ADD_PARTITION_NO_NEW_PARTITION',
           'ER_WARN_ALLOWED_PACKET_OVERFLOWED', 'ER_SELECT_REDUCED',
           'ER_TRG_IN_WRONG_SCHEMA', 'ER_SP_NO_AGGREGATE',
           'ER_UNSUPPORTED_EXTENSION', 'ER_INSERT_INFO',
           'ER_WARN_DEPRECATED_SYNTAX_WITH_VER',
           'ER_ACCESS_DENIED_ERROR', 'ER_TRG_NO_DEFINER',
           'ER_DUP_ENTRY', 'ER_CANT_SET_WD', 'ER_ERROR_ON_WRITE',
           'ER_OUT_OF_RESOURCES', 'ER_EVENT_DOES_NOT_EXIST',
           'ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG', 'ER_DB_DROP_EXISTS',
           'ER_SLAVE_THREAD', 'ER_COLLATION_CHARSET_MISMATCH',
           'ER_LOG_PURGE_NO_FILE', 'ER_MISSING_SKIP_SLAVE',
           'ER_KEY_PART_0', 'ER_NEED_REPREPARE',
           'ER_SP_CANT_SET_AUTOCOMMIT', 'ER_SP_BADSTATEMENT', 'ER_NO',
           'ER_TOO_LONG_KEY', 'ER_NO_SUCH_USER',
           'ER_NEW_ABORTING_CONNECTION', 'ER_SUBPARTITION_ERROR',
           'ER_SP_STORE_FAILED', 'ER_NONUNIQ_TABLE',
           'ER_WRONG_NAME_FOR_CATALOG', 'ER_QUERY_ON_MASTER',
           'ER_NO_SUCH_THREAD', 'ER_BLOBS_AND_NO_TERMINATED',
           'ER_SP_GOTO_IN_HNDLR', 'ER_CANT_RENAME_LOG_TABLE',
           'ER_CUT_VALUE_GROUP_CONCAT', 'ER_CRASHED_ON_USAGE',
           'ER_WRONG_STRING_LENGTH', 'ER_FORCING_CLOSE',
           'ER_WRONG_USAGE',
           'ER_EVENT_INTERVAL_NOT_POSITIVE_OR_TOO_BIG',
           'ER_PARSE_ERROR', 'ER_NISAMCHK', 'ER_SIZE_OVERFLOW_ERROR',
           'ER_PS_NO_RECURSION', 'ER_FPARSER_EOF_IN_COMMENT',
           'ER_DROP_INDEX_FK', 'ER_VIEW_INVALID', 'ER_XAER_NOTA',
           'ER_PARTITION_NO_TEMPORARY', 'ER_XAER_RMERR',
           'ER_UPDATE_INFO', 'ER_TOO_MANY_PARTITIONS_ERROR',
           'ER_PARTITION_REQUIRES_VALUES_ERROR', 'ER_NOT_KEYFILE',
           'ER_TABLESPACE_AUTO_EXTEND_ERROR', 'ER_STACK_OVERRUN',
           'ER_NO_DB_ERROR', 'ER_PARTITION_WRONG_NO_SUBPART_ERROR',
           'ER_CANT_CREATE_DB', 'ER_PARTITION_WRONG_NO_PART_ERROR',
           'ER_CANNOT_LOAD_FROM_TABLE', 'ER_CONFLICTING_DECLARATIONS',
           'ER_UPDATE_LOG_DEPRECATED_IGNORED',
           'ER_BAD_SLAVE_UNTIL_COND', 'ER_NO_RAID_COMPILED',
           'ER_TABLE_MUST_HAVE_COLUMNS', 'ER_VIEW_OTHER_USER',
           'ER_READY', 'ER_SP_WRONG_NO_OF_ARGS', 'ER_UDF_NO_PATHS',
           'ER_TOO_BIG_SELECT', 'ER_FSEEK_FAIL',
           'ER_INVALID_GROUP_FUNC_USE', 'ER_CANT_CREATE_TABLE',
           'ER_SP_BAD_SQLSTATE', 'ER_LOAD_DATA_INVALID_COLUMN',
           'ER_CANT_GET_WD', 'ER_WRONG_NAME_FOR_INDEX',
           'ER_UNKNOWN_TARGET_BINLOG', 'ER_ERROR_DURING_CHECKPOINT',
           'ER_BAD_HOST_ERROR', 'ER_SP_PROC_TABLE_CORRUPT',
           'ER_SLAVE_AMBIGOUS_EXEC_MODE', 'ER_VIEW_RECURSIVE',
           'ER_TRG_CANT_CHANGE_ROW', 'ER_PARTITION_FUNCTION_FAILURE',
           'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD', 'ER_EVENT_SAME_NAME',
           'ER_WRONG_SUM_SELECT', 'ER_ERROR_DURING_FLUSH_LOGS',
           'ER_WRONG_PARAMCOUNT_TO_NATIVE_FCT',
           'ER_BINLOG_UNSAFE_ROUTINE', 'ER_WARN_FIELD_RESOLVED',
           'ER_DUP_ENTRY_AUTOINCREMENT_CASE', 'ER_VIEW_SELECT_CLAUSE',
           'ER_ZLIB_Z_DATA_ERROR', 'ER_WARN_TOO_MANY_RECORDS',
           'ER_CREATE_FILEGROUP_FAILED', 'ER_FPARSER_TOO_BIG_FILE',
           'ER_DB_DROP_RMDIR',
           'ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE',
           'ER_UNKNOWN_KEY_CACHE', 'ER_FOREIGN_DATA_STRING_INVALID',
           'ER_TABLE_EXISTS_ERROR', 'ER_EVENT_INVALID_CREATION_CTX',
           'ER_DROP_PARTITION_NON_EXISTENT', 'ER_DIFF_GROUPS_PROC',
           'ER_SLAVE_IGNORED_SSL_PARAMS',
           'ER_DELAYED_INSERT_TABLE_LOCKED', 'ER_DIVISION_BY_ZERO',
           'ER_BAD_NULL_ERROR', 'ER_SP_DUP_COND',
           'ER_CANT_CREATE_SROUTINE', 'ER_USERNAME',
           'ER_BAD_DB_ERROR', 'ER_WRONG_SIZE_NUMBER',
           'ER_PARTITION_ENTRY_ERROR', 'ER_BLOB_USED_AS_KEY',
           'ER_TRG_ON_VIEW_OR_TEMP_TABLE',
           'ER_UNKNOWN_STORAGE_ENGINE', 'ER_OPERAND_COLUMNS',
           'ER_FOREIGN_DUPLICATE_KEY', 'ER_XAER_OUTSIDE',
           'ER_KEY_DOES_NOT_EXITS', 'ER_USER_LIMIT_REACHED',
           'ER_CANT_AGGREGATE_NCOLLATIONS',
           'ER_PROC_AUTO_REVOKE_FAIL', 'ER_TOO_BIG_DISPLAYWIDTH',
           'ER_CANT_CREATE_HANDLER_FILE',
           'ER_CANT_AGGREGATE_2COLLATIONS',
           'ER_SLAVE_WAS_NOT_RUNNING', 'ER_DBACCESS_DENIED_ERROR',
           'ER_NO_DEFAULT_FOR_FIELD',
           'ER_EVENT_CANNOT_ALTER_IN_THE_PAST',
           'ER_MIX_HANDLER_ERROR',
           'ER_FPARSER_EOF_IN_UNKNOWN_PARAMETER',
           'ER_LIMITED_PART_RANGE', 'ER_SP_CURSOR_AFTER_HANDLER',
           'ER_LOCK_OR_ACTIVE_TRANSACTION', 'ER_WRONG_OUTER_JOIN',
           'ER_UNKNOWN_SYSTEM_VARIABLE', 'ER_BINLOG_PURGE_EMFILE',
           'ER_WRONG_ARGUMENTS', 'ER_UNKNOWN_STMT_HANDLER',
           'ER_NO_TABLES_USED', 'ER_WARN_DEPRECATED_SYNTAX',
           'ER_BINLOG_UNSAFE_STATEMENT', 'ER_LOCK_WAIT_TIMEOUT',
           'ER_NO_FILE_MAPPING', 'ER_WRONG_VALUE',
           'ER_ERROR_DURING_COMMIT', 'ER_HOST_IS_BLOCKED',
           'ER_NONEXISTING_PROC_GRANT', 'ER_BINLOG_PURGE_FATAL_ERR',
           'ER_VIEW_WRONG_LIST']
